/**
 * Serializes GitHub Actions workflow configurations to YAML strings.
 *
 * @module
 */

import type { WorkflowConfig } from './workflows/index.js'

/**
 * Serializes a workflow configuration object to a YAML string suitable
 * for writing to `.github/workflows/*.yml`.
 *
 * @param config - The workflow configuration to serialize.
 * @returns The YAML string representation of the workflow.
 */
export const toYAML = (config: WorkflowConfig): string => {
  return stringify(config, 0)
}

/**
 * Recursively serializes a JavaScript value to YAML format with proper
 * indentation, quoting, and array/object formatting.
 *
 * @param value - The value to serialize (string, number, boolean, array, or object).
 * @param indent - The current indentation depth (number of 2-space levels).
 * @returns The YAML string fragment for this value.
 */
const stringify = (value: unknown, indent: number): string => {
  const spaces = '  '.repeat(indent)

  if (value === null || value === undefined) {
    return 'null'
  }

  if (typeof value === 'boolean') {
    return value.toString()
  }

  if (typeof value === 'number') {
    return value.toString()
  }

  if (typeof value === 'string') {
    // Check if string needs quoting
    if (
      value.includes(':') ||
      value.includes('#') ||
      value.includes("'") ||
      value.includes('"') ||
      value.includes('\n') ||
      value.startsWith('$') ||
      value === 'true' ||
      value === 'false' ||
      value === 'null' ||
      value === ''
    ) {
      // Use single quotes and escape internal single quotes
      return `'${value.replace(/'/g, "''")}'`
    }
    return value
  }

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'

    // Check if it's a simple array (all primitives)
    const isSimple = value.every(
      (v) => typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean',
    )

    if (isSimple && value.length <= 3) {
      return `[${value.map((v) => stringify(v, 0)).join(', ')}]`
    }

    return value
      .map((v) => {
        const str = stringify(v, indent + 1)
        if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
          // Object in array - first key on same line as dash
          const lines = str.split('\n')
          return `${spaces}- ${lines[0].trim()}\n${lines
            .slice(1)
            .map((l) => spaces + '  ' + l.trim())
            .join('\n')}`.trimEnd()
        }
        return `${spaces}- ${str}`
      })
      .join('\n')
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
    if (entries.length === 0) return '{}'

    return entries
      .map(([key, val]) => {
        // Handle keys with special characters
        const safeKey = key.includes('-') || key.includes(' ') ? `'${key}'` : key
        const valStr = stringify(val, indent + 1)

        if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
          return `${spaces}${safeKey}:\n${valStr}`
        }
        if (Array.isArray(val) && val.length > 0 && typeof val[0] === 'object') {
          return `${spaces}${safeKey}:\n${valStr}`
        }

        return `${spaces}${safeKey}: ${valStr}`
      })
      .join('\n')
  }

  return String(value)
}

/**
 * Generates a complete workflow file with a header comment indicating it was
 * auto-generated. The output is ready to write to `.github/workflows/`.
 *
 * @param config - The workflow configuration to generate.
 * @returns The complete YAML file content including the auto-generated header.
 */
export const generateWorkflow = (config: WorkflowConfig): string => {
  const header = `# Generated by @molecule/api-ci-github-actions
# Do not edit manually - regenerate with: npx molecule ci generate

`
  return header + toYAML(config)
}

/**
 * Returns the conventional file path for a GitHub Actions workflow file.
 *
 * @param name - The workflow name (e.g. `'ci'`, `'release'`).
 * @returns The path relative to the repo root (e.g. `.github/workflows/ci.yml`).
 */
export const workflowPath = (name: string): string => `.github/workflows/${name}.yml`
