/**
 * Generates the Modal `app.py` that runs a registry image as a web server.
 *
 * Modal has no REST deploy API: an app is Python, deployed with `modal deploy`.
 * Verified 2026-09-30 in Modal's own sources and docs —
 * `App.function(image=, gpu=, cpu=, memory=, min_containers=, max_containers=,
 * scaledown_window=, secrets=, region=, timeout=)` (github.com/modal-labs/modal-client
 * py/modal/app.py); `Image.from_registry(tag, secret=None, *, add_python=None)` and
 * `Image.env(vars)` (py/modal/_image.py); `@modal.concurrent(max_inputs=)`
 * (py/modal/_partial_function.py); `@modal.web_server(port, *, startup_timeout=5.0,
 * label=None, requires_proxy_auth=False)` — https://modal.com/docs/reference/modal.web_server ;
 * GPU strings `T4, L4, A10, L40S, A100, A100-40GB, A100-80GB, H100, H200, B200` —
 * https://modal.com/docs/guide/gpu
 *
 * @module
 */

import type { ModelEndpointSpec } from '@molecule/api-model-hosting'

/** GPU types by memory, smallest first. */
export const MODAL_GPUS: ReadonlyArray<{ id: string; vramGb: number }> = [
  { id: 'T4', vramGb: 16 },
  { id: 'L4', vramGb: 24 },
  { id: 'A10', vramGb: 24 },
  { id: 'A100-40GB', vramGb: 40 },
  { id: 'L40S', vramGb: 48 },
  { id: 'A100-80GB', vramGb: 80 },
  { id: 'H100', vramGb: 80 },
  { id: 'H200', vramGb: 141 },
  { id: 'B200', vramGb: 180 },
]

/**
 * Renders a JSON-shaped value as a Python literal.
 *
 * @param value - The value.
 * @returns Python source.
 */
export function toPython(value: unknown): string {
  if (value === null || value === undefined) return 'None'
  if (value === true) return 'True'
  if (value === false) return 'False'
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'None'
  if (typeof value === 'string') return JSON.stringify(value)
  if (Array.isArray(value)) return `[${value.map(toPython).join(', ')}]`
  return `{${Object.entries(value as Record<string, unknown>)
    .map(([k, v]) => `${JSON.stringify(k)}: ${toPython(v)}`)
    .join(', ')}}`
}

/**
 * The Modal GPU string for a spec: the named one, or the smallest that fits.
 *
 * @param spec - The endpoint spec.
 * @returns A GPU string, or `null` for CPU.
 */
export function gpuFor(spec: ModelEndpointSpec): string | null {
  const a = spec.accelerator
  if (a.kind === 'cpu') return null
  if (a.model) return a.model
  const fit = MODAL_GPUS.find((g) => g.vramGb >= a.minVramGb)
  if (!fit) throw new Error(`model-hosting (modal): no GPU with ≥ ${a.minVramGb} GB`)
  return fit.id
}

/**
 * The `app.py` for a spec.
 *
 * @param spec - The endpoint spec (`command` required: Modal starts the server from Python).
 * @param opts - Python and startup options.
 * @param opts.addPython - Python version to add to an image without one.
 * @param opts.startupTimeoutSeconds - How long the server may take to listen.
 * @returns Python source.
 */
export function appSource(
  spec: ModelEndpointSpec,
  opts: { addPython?: string; startupTimeoutSeconds: number },
): string {
  if (!spec.command?.length) {
    throw new Error(
      'model-hosting (modal): `command` is required — Modal starts the server from a Python function, not the image entrypoint',
    )
  }
  const gpu = gpuFor(spec)
  const fn: Record<string, unknown> = {
    min_containers: spec.scaling.minInstances,
    max_containers: spec.scaling.maxInstances,
    scaledown_window: spec.scaling.idleTimeoutSeconds,
    timeout: 86_400,
  }
  const kwargs = [
    'image=image',
    ...(gpu ? [`gpu=${toPython(gpu)}`] : []),
    ...(spec.cpu ? [`cpu=${toPython(spec.cpu)}`] : []),
    ...(spec.memoryMb ? [`memory=${toPython(spec.memoryMb)}`] : []),
    ...Object.entries(fn).map(([k, v]) => `${k}=${toPython(v)}`),
    ...(spec.region === 'us' || spec.region === 'eu' || /^[a-z]+-[a-z]+-?\d*$/.test(spec.region)
      ? [`region=${toPython(spec.region)}`]
      : []),
    ...(spec.secretEnv && Object.keys(spec.secretEnv).length
      ? [`secrets=[modal.Secret.from_dict(${toPython(spec.secretEnv)})]`]
      : []),
  ]
  const imageArgs = opts.addPython ? `, add_python=${toPython(opts.addPython)}` : ''
  return [
    '# Generated by @molecule/api-model-hosting-modal — edits are overwritten on the next deploy.',
    'import subprocess',
    '',
    'import modal',
    '',
    `image = modal.Image.from_registry(${toPython(spec.image)}${imageArgs}).env(${toPython(spec.env ?? {})})`,
    `app = modal.App(${toPython(spec.name)})`,
    '',
    '',
    `@app.function(${kwargs.join(', ')})`,
    ...(spec.scaling.concurrency
      ? [`@modal.concurrent(max_inputs=${toPython(spec.scaling.concurrency)})`]
      : []),
    `@modal.web_server(${spec.port}, startup_timeout=${opts.startupTimeoutSeconds}, label=${toPython(spec.name)}, requires_proxy_auth=${toPython(spec.access === 'private')})`,
    'def serve():',
    `    subprocess.Popen(${toPython(spec.command)})`,
    '',
  ].join('\n')
}
