/**
 * Browser guard — @molecule/api-permissions-casbin is SERVER-ONLY.
 *
 * Generated by scripts/gen-browser-guards.mjs (workspace root) — edit THAT, not this.
 * Evaluating a server package in a browser bundle is always an import-graph mistake
 * (node APIs, secrets); without this guard it surfaces as a cryptic downstream crash
 * ("Buffer is not defined") far from the culprit. Throwing here names the package and
 * the fix at the exact moment the client bundle evaluates it. jsdom tests and SSR are
 * unaffected: the throw requires browser globals AND the absence of a node runtime.
 */
const g = globalThis as {
  window?: unknown
  document?: unknown
  process?: { versions?: { node?: string } }
}
if (g.window !== undefined && g.document !== undefined && !g.process?.versions?.node) {
  throw new Error(
    '@molecule/api-permissions-casbin is SERVER-ONLY: it was bundled into browser/client code. Import it only ' +
      'from server code (a server route/function or your API), or dynamic-import it inside ' +
      'the server handler — never from components or shared client modules, and never ' +
      'polyfill Buffer/process to silence this.',
  )
}
export {}
