/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { StaleWhileRevalidate } from 'workbox-strategies'

/** The shape of every entry vite-plugin-pwa injects into `__WB_MANIFEST`. */
export type PrecacheEntry = { url: string; revision: string | null }

/**
 * Wires the default service worker — precache manifest, app-shell
 * navigation routing, image cache with StaleWhileRevalidate, and a
 * SKIP_WAITING message handler.
 *
 * Must be called from the app's `src/service-worker.ts` so
 * vite-plugin-pwa's manifest injection sees the `__WB_MANIFEST`
 * reference inside the SW file (the plugin scans the SW source for
 * the token at build time).
 *
 * @example
 * ```ts
 * /// <reference lib="webworker" />
 * import { setupDefaultServiceWorker } from '@molecule/app-service-worker-default'
 *
 * declare const self: ServiceWorkerGlobalScope & {
 *   __WB_MANIFEST: Array<{ url: string; revision: string | null }>
 * }
 *
 * setupDefaultServiceWorker(self, self.__WB_MANIFEST)
 * ```
 */
export function setupDefaultServiceWorker(
  worker: ServiceWorkerGlobalScope,
  manifest: PrecacheEntry[],
): void {
  clientsClaim()

  // Precache all assets generated by the build process.
  precacheAndRoute(manifest)

  // App Shell-style routing: all navigation requests are fulfilled
  // with index.html so client-side routing works offline.
  const fileExtensionRegexp = /\/[^/?]+\.[^/]+$/
  registerRoute(({ request, url }: { request: Request; url: URL }) => {
    if (request.mode !== 'navigate') return false
    if (url.pathname.startsWith('/_')) return false
    if (url.pathname.match(fileExtensionRegexp)) return false
    return true
  }, createHandlerBoundToURL('/index.html'))

  // Cache images with a StaleWhileRevalidate strategy.
  registerRoute(
    ({ url }: { url: URL }) =>
      url.origin === worker.location.origin && url.pathname.endsWith('.png'),
    new StaleWhileRevalidate({
      cacheName: 'images',
      plugins: [new ExpirationPlugin({ maxEntries: 50 })],
    }),
  )

  // Listen for messages from the application.
  worker.addEventListener('message', (event) => {
    switch (event.data?.type) {
      case 'SKIP_WAITING':
        return event.waitUntil(worker.skipWaiting())
      default:
        return
    }
  })
}
