/// <reference lib="webworker" />

import { clientsClaim } from 'workbox-core'
import { ExpirationPlugin } from 'workbox-expiration'
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { StaleWhileRevalidate } from 'workbox-strategies'

/** The shape of every entry vite-plugin-pwa injects into `__WB_MANIFEST`. */
export type PrecacheEntry = { url: string; revision: string | null }

/**
 * Common web image extensions the default image cache matches (lower-case,
 * without the leading dot). Covers the raster + vector formats a modern app
 * actually ships — not just `.png`.
 */
export const DEFAULT_IMAGE_EXTENSIONS: readonly string[] = [
  'png',
  'jpg',
  'jpeg',
  'webp',
  'avif',
  'gif',
  'svg',
  'ico',
]

/**
 * Options for {@link setupDefaultServiceWorker}. All fields are optional —
 * sensible defaults derive the base path from the SW registration scope and
 * cache all common web image formats.
 */
export interface DefaultServiceWorkerOptions {
  /**
   * The precached URL the app-shell navigation fallback resolves to.
   *
   * Defaults to `index.html` resolved against `self.registration.scope`, so an
   * app built with a non-root Vite `base` (e.g. served under `/app/`) falls
   * back to the correct `/app/index.html` — NOT a hardcoded `/index.html`,
   * which would 404/mis-route under a sub-path. Pass an explicit value to
   * override (must match a URL present in the precache manifest).
   */
  navigationFallback?: string
  /**
   * File extensions (lower-case, no leading dot) the image cache matches.
   * Defaults to {@link DEFAULT_IMAGE_EXTENSIONS}.
   */
  imageExtensions?: readonly string[]
  /** Max entries retained by the image cache. Defaults to `50`. */
  imageCacheMaxEntries?: number
}

/**
 * Resolve the default navigation-fallback URL from the SW registration scope
 * so a non-root `base` path works out of the box.
 *
 * For a worker registered at `https://host/app/service-worker.js` the scope is
 * `https://host/app/`, so the fallback resolves to `/app/index.html`. Falls
 * back to `/index.html` only when the scope is unavailable (e.g. a bare test
 * double) or unparseable.
 *
 * @param worker - The service-worker global scope.
 * @returns The base-aware `index.html` path.
 */
function resolveNavigationFallback(worker: ServiceWorkerGlobalScope): string {
  const scope = worker.registration?.scope
  if (scope) {
    try {
      return new URL('index.html', scope).pathname
    } catch (_error) {
      // A malformed/relative scope can't be resolved into an absolute URL;
      // the root fallback below is the only safe default in that case.
    }
  }
  return '/index.html'
}

/**
 * Wires the default service worker — precache manifest, base-aware app-shell
 * navigation routing, a same-origin multi-format image cache with
 * StaleWhileRevalidate, and a SKIP_WAITING message handler.
 *
 * Must be called from the app's `src/service-worker.ts` so the
 * build-time manifest injection (vite-plugin-pwa `injectManifest`,
 * workbox-webpack-plugin, workbox-cli) sees the `__WB_MANIFEST`
 * reference inside the SW file (the tool scans the SW source for
 * the token at build time). See the package-level example.
 *
 * @param worker - The service-worker global scope (`self`).
 * @param manifest - The precache manifest (`self.__WB_MANIFEST`).
 * @param options - Optional overrides — see {@link DefaultServiceWorkerOptions}.
 *   By default the navigation fallback is derived from the registration scope
 *   (base-path aware) and the image cache matches all common web image formats.
 */
export function setupDefaultServiceWorker(
  worker: ServiceWorkerGlobalScope,
  manifest: PrecacheEntry[],
  options: DefaultServiceWorkerOptions = {},
): void {
  clientsClaim()

  // Precache all assets generated by the build process.
  precacheAndRoute(manifest)

  // App Shell-style routing: all navigation requests are fulfilled with
  // index.html so client-side routing works offline. The fallback URL is
  // base-path aware (derived from the registration scope), so apps served
  // under a sub-path resolve to `<base>/index.html`, not a hardcoded root.
  const navigationFallback = options.navigationFallback ?? resolveNavigationFallback(worker)
  const fileExtensionRegexp = /\/[^/?]+\.[^/]+$/
  registerRoute(({ request, url }: { request: Request; url: URL }) => {
    if (request.mode !== 'navigate') return false
    if (url.pathname.startsWith('/_')) return false
    if (url.pathname.match(fileExtensionRegexp)) return false
    return true
  }, createHandlerBoundToURL(navigationFallback))

  // Cache same-origin images with a StaleWhileRevalidate strategy. Matches all
  // common web image formats (png/jpg/jpeg/webp/avif/gif/svg/ico), not PNG only.
  const imageExtensions = options.imageExtensions ?? DEFAULT_IMAGE_EXTENSIONS
  const imageExtensionRegexp = new RegExp(`\\.(?:${imageExtensions.join('|')})$`, 'i')
  registerRoute(
    ({ url }: { url: URL }) =>
      url.origin === worker.location.origin && imageExtensionRegexp.test(url.pathname),
    new StaleWhileRevalidate({
      cacheName: 'images',
      plugins: [new ExpirationPlugin({ maxEntries: options.imageCacheMaxEntries ?? 50 })],
    }),
  )

  // Listen for messages from the application.
  worker.addEventListener('message', (event) => {
    switch (event.data?.type) {
      case 'SKIP_WAITING':
        return event.waitUntil(worker.skipWaiting())
      default:
        return
    }
  })
}
