import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { editBlocksOf } from '../history.js'
import { provider } from '../provider.js'

// Generated by replaying aider/io.py's own writers (user_input, ai_output,
// tool_output, append_chat_history) over two sessions — 2026-09-29.
const history = readFileSync(join(__dirname, 'fixtures', '.aider.chat.history.md'), 'utf8')

describe('detect', () => {
  it('recognizes the history file', () => {
    expect(provider.detect({ text: history })).toBe(true)
  })

  it('refuses other formats', () => {
    expect(provider.detect({ text: '# Notes\n\n#### A heading\n\ntext' })).toBe(false)
    expect(provider.detect({ text: '# Codex conversation\n\n## User\n\nhi' })).toBe(false)
    expect(() => provider.read({ text: 'hello', fileName: 'x.md' })).toThrow(
      /Not an Aider transcript \(x\.md\)/,
    )
  })
})

describe('the chat history', () => {
  const s = provider.read({ text: history })

  it('reads both sessions in order, with the multi-line prompt joined and slash commands left out', () => {
    expect(s).toMatchObject({ format: 'aider', harness: 'Aider', startedAt: '2026-09-28T09:00:00' })
    expect(s.model).toBeUndefined() // two sessions, two models
    expect(s.turns.map((t) => t.role)).toEqual(['user', 'assistant', 'user', 'assistant'])
    expect(s.turns[0].text).toBe('Create notes.md with a heading\nand one sentence about logs.')
    expect(s.turns[2].text).toBe('Rename the heading to Field notes.')
  })

  it('keeps a reply’s own > quote and #### heading, and never Aider’s own lines', () => {
    expect(s.turns[1].text).toContain('> Tip: keep notes short.')
    expect(s.turns[1].text).not.toContain('Tokens:')
    expect(s.turns[3].text.startsWith('#### Plan\nRewrite the file')).toBe(true)
  })

  it('names each reply’s model from the announcement before it', () => {
    expect(s.turns[1].model).toBe('anthropic/claude-sonnet-4-5')
    expect(s.turns[3].model).toBe('gpt-5.3')
  })

  it('reads applied edits: an empty SEARCH is a new file, the whole format is the fenced block', () => {
    expect(s.turns[1].files).toEqual([
      {
        path: 'notes.md',
        kind: 'create',
        text: '# Notes\n\nLogs show what happened first.',
        complete: true,
      },
    ])
    expect(s.turns[3].files).toEqual([
      {
        path: 'notes.md',
        kind: 'create',
        text: '# Field notes\n\nLogs show what happened first.',
        complete: true,
      },
    ])
  })

  it('names one model when the file holds a single session', () => {
    const first = history.split('# aider chat started at 2026-09-29')[0]
    expect(provider.read({ text: first }).model).toBe('anthropic/claude-sonnet-4-5')
  })
})

describe('editBlocksOf', () => {
  it('reads a SEARCH/REPLACE edit with its file name', () => {
    const reply =
      'src/app.py\n```python\n<<<<<<< SEARCH\nx = 1\n=======\nx = 2\n>>>>>>> REPLACE\n```'
    expect(editBlocksOf(reply)).toEqual([{ path: 'src/app.py', search: 'x = 1', replace: 'x = 2' }])
  })
})
