/**
 * Tailwind CSS UI components for molecule.dev.
 *
 * Provides pre-built, accessible UI components using Tailwind CSS classes.
 * These are framework-agnostic class strings that can be used with any
 * rendering library (React, Vue, Svelte, etc.).
 *
 * @example
 * ```typescript
 * // 1. Wire the ClassMap once at startup (bonds.ts):
 * import { setClassMap } from '@molecule/app-ui'
 * import { classMap } from '@molecule/app-ui-tailwind'
 *
 * setClassMap(classMap)
 *
 * // 2. In the app's Tailwind v4 CSS entry (e.g. src/index.css):
 * //      @import 'tailwindcss';
 * //      @import '@molecule/app-ui-tailwind/base.css';   <- theme tokens
 * //      @source "../node_modules/@molecule/app-ui-tailwind/dist";  <- keep
 * //        Tailwind's purge from stripping the classes this package emits
 * // (Scaffolded molecule apps already have both — this is only needed when
 * //  integrating into an app not generated by mlcl.)
 *
 * // 3. Resolve classes anywhere via the ClassMap — never hardcode Tailwind:
 * import { getClassMap } from '@molecule/app-ui'
 * const cm = getClassMap()
 * element.className = cm.button({ color: 'primary', size: 'md' })
 * ```
 *
 * @remarks
 * Theming / where colors come from: the class strings here use semantic tokens
 * (`bg-primary`, `text-primary`, `bg-surface`, …), NOT literal palette classes
 * (`bg-blue-600`). Those tokens are defined in this package's `base.css`
 * `@theme` block, where the ~15 CORE colors read
 * `--color-primary: var(--mol-color-primary, <default>)` (from the
 * `@molecule/app-theme` bond) and every other token (hover, container, Material
 * on-*, surface tiers) is AUTO-DERIVED from the cores via `color-mix()` — so
 * changing one core recolors all its shades.
 *
 * To recolor a scaffolded app: edit `app/src/theme.css` (the `--color-*`
 * variables, `:root` = light, `[data-mol-mode='dark']` = dark) when it exists —
 * it overrides everything here. Only when there is no `theme.css` do the
 * `--mol-color-*` from the theme bond drive the palette. NEVER hardcode a literal
 * Tailwind color class in a component — it breaks theming and the safelist.
 *
 * @module
 */

export * from './classMap.js'
export * from './components.js'
export * from './layout.js'
export * from './types.js'
export * from './utilities.js'
