-- Schema for @molecule/api-leaderboard.
--
-- Portable by design: this DDL is standard SQL that runs UNCHANGED on
-- PostgreSQL and SQLite, matching the service's dialect-agnostic contract
-- (the service touches the database only through @molecule/api-database's
-- abstract DataStore — no raw SQL). It deliberately uses NO dialect-only
-- functions:
--   * Row ids are generated by the DataStore's `create()` (which injects a
--     UUID when the caller omits one) — NOT a DB-side `gen_random_uuid()`,
--     which SQLite lacks. So the `id` columns carry no DB default.
--   * Timestamp defaults use the standard `CURRENT_TIMESTAMP`, not Postgres's
--     `now()` (also absent on SQLite).
-- The `UUID`/`TIMESTAMPTZ` type names and the partial index below are
-- PostgreSQL-native and accepted by SQLite via type affinity. MySQL's stricter
-- parser has them normalised automatically by the @molecule/api-database-mysql
-- bond at migrate time (UUID→CHAR(36), TIMESTAMPTZ→TIMESTAMP, partial-index
-- predicate dropped) — so no manual porting is required on any of the three
-- official database bonds.

CREATE TABLE IF NOT EXISTS "leaderboard_events" (
  "id" UUID PRIMARY KEY,
  "user_id" UUID NOT NULL,
  "metric" VARCHAR(64) NOT NULL,
  "value" DOUBLE PRECISION NOT NULL,
  "scope_key" VARCHAR(128),
  "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_leaderboard_events_metric" ON "leaderboard_events" ("metric");
CREATE INDEX IF NOT EXISTS "idx_leaderboard_events_user" ON "leaderboard_events" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_leaderboard_events_metric_occurred_at"
  ON "leaderboard_events" ("metric", "occurred_at");
CREATE INDEX IF NOT EXISTS "idx_leaderboard_events_scope"
  ON "leaderboard_events" ("metric", "scope_key", "occurred_at")
  WHERE "scope_key" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "leaderboard_rollups" (
  "id" UUID PRIMARY KEY,
  "metric" VARCHAR(64) NOT NULL,
  "window_kind" VARCHAR(16) NOT NULL,
  "window_start" TIMESTAMPTZ NOT NULL,
  "window_end" TIMESTAMPTZ NOT NULL,
  "scope_key" VARCHAR(128),
  "user_id" UUID NOT NULL,
  "score" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "rank" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("metric", "window_kind", "window_start", "scope_key", "user_id")
);

CREATE INDEX IF NOT EXISTS "idx_leaderboard_rollups_lookup"
  ON "leaderboard_rollups" ("metric", "window_kind", "window_start", "scope_key", "rank");
