/**
 * Docker Compose YAML generator for staging environments.
 *
 * Generates a `docker-compose.staging-{slug}.yml` file tailored to
 * the branch-specific environment.
 *
 * @module
 */

import type { StagingEnvironment } from '@molecule/api-staging'

/**
 * Configuration for Docker Compose file generation.
 */
export interface ComposeGeneratorConfig {
  /** Allocated API port on the host. */
  apiPort: number

  /** Allocated App port on the host. */
  appPort: number

  /** Allocated database port on the host. */
  dbPort: number

  /** Relative path from compose file to the API project root. */
  apiContext?: string

  /** Relative path from compose file to the App project root. */
  appContext?: string

  /** Path to generated Dockerfiles directory, relative to the compose file. */
  dockerfilePath?: string
}

/**
 * Generates a Docker Compose YAML string for a staging environment.
 *
 * The API service uses runtime env_file layering (Node.js reads process.env).
 * The App service uses Docker build args for VITE_* variables (Vite inlines
 * them at build time; runtime env vars have no effect on the served bundle).
 *
 * @param env - The staging environment descriptor.
 * @param config - Port and path configuration.
 * @returns A Docker Compose YAML string.
 */
export function generateComposeFile(
  env: StagingEnvironment,
  config: ComposeGeneratorConfig,
): string {
  const network = `staging-${env.slug}`
  const volume = `staging-${env.slug}-db`
  const apiContext = config.apiContext ?? '../../api'
  const appContext = config.appContext ?? '../../app'
  const dockerfilePath = config.dockerfilePath ?? '.'

  return `# Generated by @molecule/api-staging-docker-compose
# Branch: ${env.branch}
# Slug: ${env.slug}

services:
  api:
    build:
      context: ${apiContext}
      dockerfile: ${dockerfilePath}/Dockerfile.api
    ports:
      - "${config.apiPort}:4000"
    env_file:
      - ../../.env
      - ../../.env.staging
      - ../../.env.staging.${env.slug}
    environment:
      - DATABASE_URL=postgresql://dev:dev@db:5432/molecule
      - NODE_ENV=staging
      - STAGING_SLUG=${env.slug}
      - STAGING_BRANCH=${env.branch}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ${network}

  app:
    build:
      context: ${appContext}
      dockerfile: ${dockerfilePath}/Dockerfile.app
      args:
        VITE_API_URL: http://localhost:${config.apiPort}/api
    ports:
      - "${config.appPort}:80"
    networks:
      - ${network}

  db:
    image: postgres:16
    ports:
      - "${config.dbPort}:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=molecule
    volumes:
      - ${volume}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ${network}

volumes:
  ${volume}:

networks:
  ${network}:
    name: ${network}
`
}
