/**
 * Dockerfile and Nginx config generators for staging environments.
 *
 * Generates multi-stage Dockerfiles for both API (Node.js) and App
 * (Vite build → Nginx serve) containers, plus an SPA-compatible
 * Nginx configuration.
 *
 * @module
 */

/**
 * Generates a multi-stage Dockerfile for the API server.
 *
 * Stage 1 (build): installs all deps, compiles TypeScript.
 * Stage 2 (runtime): copies compiled output, installs production deps only.
 *
 * @returns Dockerfile content as a string.
 */
export function generateApiDockerfile(): string {
  return `# Generated by @molecule/api-staging-docker-compose
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 4000
CMD ["node", "dist/server.js"]
`
}

/**
 * Generates a multi-stage Dockerfile for the frontend app.
 *
 * Stage 1 (build): installs deps, injects Vite env vars via Docker ARG,
 * then runs the Vite build. ARG → ENV ensures \`process.env.VITE_*\` is
 * available to Vite at build time (takes precedence over .env files).
 *
 * Stage 2 (serve): copies built static assets into Nginx.
 *
 * @param envVars - Build-time environment variables to inject (e.g. \`{ VITE_API_URL: '...' }\`).
 * @returns Dockerfile content as a string.
 */
export function generateAppDockerfile(envVars: Record<string, string> = {}): string {
  const argLines = Object.keys(envVars)
    .map((key) => `ARG ${key}`)
    .join('\n')
  const envLines = Object.keys(envVars)
    .map((key) => `ENV ${key}=$${key}`)
    .join('\n')

  return `# Generated by @molecule/api-staging-docker-compose
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
${argLines}
${envLines}
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
`
}

/**
 * Generates an SPA-compatible Nginx configuration.
 *
 * Uses \`try_files\` to serve \`index.html\` for all routes, which is
 * required for client-side routing (React Router, Vue Router, etc.).
 *
 * @returns Nginx config content as a string.
 */
export function generateNginxConf(): string {
  return `# Generated by @molecule/api-staging-docker-compose
server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
`
}
