/**
 * Proves the module-level `@example` in `src/index.ts` (rendered as the README
 * Quick Start) works exactly as written: the workflows are generated and
 * written for real, into a throwaway working directory.
 *
 * @module
 */
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'

import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import type { WorkflowConfig } from '../index.js'
import { commonSteps, generateWorkflow, workflowPath, workflows } from '../index.js'

describe('README @example', () => {
  const originalCwd = process.cwd()
  let repoRoot = ''

  beforeEach(() => {
    repoRoot = mkdtempSync(join(tmpdir(), 'ci-readme-example-'))
    process.chdir(repoRoot)
  })

  afterEach(() => {
    process.chdir(originalCwd)
    rmSync(repoRoot, { recursive: true, force: true })
  })

  it('writes the project CI and a custom nightly workflow as YAML files', () => {
    const writeWorkflow = (name: string, config: WorkflowConfig): void => {
      const path = workflowPath(name)
      mkdirSync(dirname(path), { recursive: true })
      writeFileSync(path, generateWorkflow(config))
    }

    writeWorkflow('ci', workflows.projectCi({ database: true }))

    writeWorkflow('nightly', {
      name: 'Nightly',
      on: { schedule: [{ cron: '0 3 * * *' }], workflow_dispatch: {} },
      jobs: {
        test: {
          'runs-on': 'ubuntu-latest',
          steps: [
            commonSteps.checkout(),
            commonSteps.setupNode('22'),
            commonSteps.npmInstall(),
            commonSteps.npmBuild(),
            commonSteps.npmTest(),
          ],
        },
      },
    })

    const ci = readFileSync(join(repoRoot, '.github/workflows/ci.yml'), 'utf8')
    expect(ci.startsWith('# Generated by @molecule/api-ci-github-actions')).toBe(true)
    expect(ci).toContain('name: CI')
    expect(ci).toMatch(/image: 'postgres:16'/)
    expect(ci).toContain('run: npm run typecheck')
    expect(ci).toMatch(/run: 'npm run db:setup'/)
    expect(ci).toContain('run: npm test')

    const nightly = readFileSync(join(repoRoot, '.github/workflows/nightly.yml'), 'utf8')
    expect(nightly).toContain('name: Nightly')
    expect(nightly).toContain('- cron: 0 3 * * *')
    expect(nightly).toContain('uses: actions/checkout@v4')
    expect(nightly).toContain("'node-version': '22'")
    expect(nightly).toContain('run: npm ci')
  })
})
