import crypto from 'node:crypto'

import { get, getAnalytics, getLogger } from '@molecule/api-bond'
import { findOne, updateById } from '@molecule/api-database'
import { t } from '@molecule/api-i18n'
import { hash } from '@molecule/api-password'
import type { MoleculeRequest } from '@molecule/api-resource'

import type * as types from '../types.js'

const analytics = getAnalytics()
const logger = getLogger()

const RESET_TOKEN_TTL_MS = 1000 * 60 * 60

/** Request body for confirming a password reset using a token. */
export interface ResetPasswordRequest extends MoleculeRequest {
  body: {
    token?: string
    password?: string
  }
}

/**
 * Confirms a password reset by validating the one-time token previously generated by
 * `forgotPassword`, then hashing and storing the new password and clearing the token.
 *
 * Token TTL is one hour. The handler responds with 400 for missing fields, 400 for
 * passwords that fail length validation (matching `updatePassword`), and 401 for
 * tokens that are unknown, expired, or already consumed.
 *
 * On success, all existing device sessions are invalidated to force a fresh login,
 * mirroring the behavior of `updatePassword`.
 *
 * @param resource - The user resource configuration (name, tableName, schema).
 * @param resource.tableName - The database table name for users.
 * @returns A request handler that responds with `{ statusCode: 200, body: { success: true } }` on success.
 */
export const resetPassword = ({ name: _name, tableName, schema: _schema }: types.Resource) => {
  return async (req: ResetPasswordRequest) => {
    try {
      const { token, password } = req.body

      if (!token) {
        return {
          statusCode: 400,
          body: {
            error: t('user.error.tokenRequired'),
            errorKey: 'user.error.tokenRequired',
          },
        }
      }

      if (!password) {
        return {
          statusCode: 400,
          body: {
            error: t('user.error.newPasswordRequired'),
            errorKey: 'user.error.newPasswordRequired',
          },
        }
      }

      if (password.length < 8) {
        return {
          statusCode: 400,
          body: {
            error: t('user.error.passwordTooShort', undefined, {
              defaultValue: 'Password must be at least 8 characters',
            }),
            errorKey: 'user.error.passwordTooShort',
          },
        }
      }

      if (password.length > 1024) {
        return {
          statusCode: 400,
          body: {
            error: t('user.error.passwordTooLong', undefined, {
              defaultValue: 'Password must be at most 1024 characters',
            }),
            errorKey: 'user.error.passwordTooLong',
          },
        }
      }

      const secrets = await findOne<types.SecretProps>(`${tableName}Secrets`, [
        { field: 'passwordResetToken', operator: '=', value: token },
      ])

      if (!secrets || !secrets.passwordResetToken || !secrets.passwordResetTokenAt) {
        return {
          statusCode: 401,
          body: {
            error: t('user.error.invalidToken'),
            errorKey: 'user.error.invalidToken',
          },
        }
      }

      // Constant-time comparison to defeat timing attacks even though the lookup
      // already matched — defense in depth.
      const a = Buffer.from(token, 'utf-8')
      const b = Buffer.from(secrets.passwordResetToken, 'utf-8')
      if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) {
        return {
          statusCode: 401,
          body: {
            error: t('user.error.invalidToken'),
            errorKey: 'user.error.invalidToken',
          },
        }
      }

      const tokenAge = Date.now() - new Date(secrets.passwordResetTokenAt).getTime()
      if (!Number.isFinite(tokenAge) || tokenAge > RESET_TOKEN_TTL_MS || tokenAge < 0) {
        return {
          statusCode: 401,
          body: {
            error: t('user.error.invalidToken'),
            errorKey: 'user.error.invalidToken',
          },
        }
      }

      const userId = (secrets as unknown as { id: string }).id
      if (!userId) {
        return {
          statusCode: 500,
          body: {
            error: t('user.error.failedToUpdatePassword'),
            errorKey: 'user.error.failedToUpdatePassword',
          },
        }
      }

      const passwordHash = await hash(password)
      await updateById(`${tableName}Secrets`, userId, {
        passwordHash,
        passwordResetToken: null,
        passwordResetTokenAt: null,
      })

      try {
        await get<{ deleteByUserId(userId: string): Promise<void> }>('device')?.deleteByUserId(
          userId,
        )
      } catch (error) {
        logger.warn('Failed to invalidate sessions after password reset', { userId, error })
      }

      analytics.track({ name: 'user.password_reset_completed', userId }).catch(() => {})

      return { statusCode: 200, body: { success: true } }
    } catch (error) {
      logger.error(error)
      return {
        statusCode: 500,
        body: {
          error: t('user.error.failedToUpdatePassword'),
          errorKey: 'user.error.failedToUpdatePassword',
        },
      }
    }
  }
}
